[project]
name = 'Astro'
version = "0.0.1"
authors = [
    {name="CoolverstukASS", email="cheburashka325@gmail.com"}
]
description="Astro"
readme="README.md"
requires-python=">=3.8"
classifiers = [
    "Programming language::Python::3"
]
